### ISSUE TITLE
Key error issues

### ISSUE THREAD

**Issue by sxdxs** [drdee255/code-Util#1]
Hi, I am having some issues with a key error callback to 

coreGenes = addGenesToDict(coreGenes,groupDict[i],seqDict)
KeyError: 'XP_AQS63436.1'

My groups.txt file looks like group1000: k599|XP_xxxxxx etc. My singletons.txt looks like k599|XP_AQSxxxxxx and my goodProteins.fasta looks like a normal fasta. I can upload them. I just can't figure out this key error! I tried switching columns and making sure the error protein ID is in the goodProteins file. I'd appreciate any help!

I made my files public and hopefully this works - https://gist.github.com/sxdxs

**Comment by microDM** [comment]
The NAMEFILE (List of names of genomes used by orthoMCL) was missing from list of files you provided. I have generated one from your goodProteins.fasta by following command:-

`grep '>' goodProteins.fasta.txt | cut -d '|' -f1 | sort | uniq | tr -d '>' >names.txt`

This command generated names.txt with list of genome ids/names like this:-

ach5
ak84
arat
at58
ata6
b110
k599
ov14
s257

After this, I ran the code with command:-

`python3 parseOrthoMCLOutput.py -g groups.txt -f goodProteins.fasta.txt -n names.txt -s singletons.txt`

This code generated all files.

**Comment by sxdxs** [comment]
Excellent thank you!! I can't believe I overlooked the names.txt. Really thought I made one. I appreciate the help, now to re-do the pipeline since I had 0 core genes with my samples!
